image: clayauld/hass-{arch}-base-python
shadow_repository: 192.168.6.53:5000
build_from:
  aarch64: "homeassistant/aarch64-base:"
  armv7: "homeassistant/armv7-base:"
  armhf: "homeassistant/armhf-base:"
  amd64: "homeassistant/amd64-base:"
  i386: "homeassistant/i386-base:"
  riscv64: "clayauld/hass-riscv64-base:"
codenotary:
  signer: clayton@clayauld.com
  base_image: clayton@clayauld.com
args:
  PYTHON_VERSION: 3.10.7
  PIP_VERSION: 22.3.0
  GPG_KEY: A035C8C19219BA821ECEA86B64E628F8D684696D
labels:
  io.hass.base.name: python
  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
